version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - /bin/bash ./build/clientBuild.sh
      - /bin/bash ./build/serverBuild.sh
  post_build:
    commands:
      - echo "Entering the post-build phase"
artifacts:
  secondary-artifacts:
    client:
      files:
        - '**/*'
      base-directory: ./build/client
    server:
      files:
        - '**/*'
      base-directory: ./build/server
